"""Add remaining models

Revision ID: 56288113140d
Revises: 96939e361599
Create Date: 2026-07-14 15:42:48.118182

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "56288113140d"
down_revision: Union[str, Sequence[str], None] = "96939e361599"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
