"""Add Data Import and Udemy Connection

Revision ID: 88e362e306f0
Revises: 56288113140d
Create Date: 2026-07-14 17:28:14.005050

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "88e362e306f0"
down_revision: Union[str, Sequence[str], None] = "56288113140d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
