"""Fix timestamp defaults

Revision ID: 96939e361599
Revises: dfdbf684e4b5
Create Date: 2026-07-14 15:17:55.693706

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "96939e361599"
down_revision: Union[str, Sequence[str], None] = "dfdbf684e4b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
