"""Init models

Revision ID: dfdbf684e4b5
Revises: f316ad330d8e
Create Date: 2026-07-14 11:07:55.262626

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dfdbf684e4b5"
down_revision: Union[str, Sequence[str], None] = "f316ad330d8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_imports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["teacher_id"], ["teachers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_imports_teacher_id"), "data_imports", ["teacher_id"], unique=False
    )
    op.create_table(
        "udemy_connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.Column("client_id_encrypted", sa.Text(), nullable=False),
        sa.Column("client_secret_encrypted", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["teacher_id"], ["teachers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_udemy_connections_teacher_id"),
        "udemy_connections",
        ["teacher_id"],
        unique=False,
    )
    op.create_table(
        "courses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.Column("udemy_course_id", sa.String(length=100), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("student_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("data_import_id", sa.UUID(), nullable=True),
        sa.Column("udemy_connection_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_import_id"], ["data_imports.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["teacher_id"], ["teachers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["udemy_connection_id"], ["udemy_connections.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("udemy_course_id"),
    )
    op.create_index(
        op.f("ix_courses_teacher_id"), "courses", ["teacher_id"], unique=False
    )
    op.create_table(
        "modules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_modules_course_id"), "modules", ["course_id"], unique=False
    )
    op.create_table(
        "student_enrollments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("udemy_student_id", sa.String(length=100), nullable=False),
        sa.Column("masked_name", sa.String(length=255), nullable=False),
        sa.Column("email_encrypted", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("progress_percent", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_student_enrollments_course_id"),
        "student_enrollments",
        ["course_id"],
        unique=False,
    )
    op.create_table(
        "lessons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("module_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("drop_off_rate", sa.Float(), nullable=True),
        sa.Column("has_warning", sa.Boolean(), nullable=True),
        sa.Column("student_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["module_id"], ["modules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lessons_course_id"), "lessons", ["course_id"], unique=False
    )
    op.create_index(
        op.f("ix_lessons_module_id"), "lessons", ["module_id"], unique=False
    )
    op.create_table(
        "ai_insights",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("raw_prompt", sa.Text(), nullable=True),
        sa.Column("raw_response", sa.Text(), nullable=True),
        sa.Column("model_version", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_insights_lesson_id"), "ai_insights", ["lesson_id"], unique=False
    )
    op.create_table(
        "learning_activities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_enrollment_id", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column("activity_type", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("video_stop_at_second", sa.Integer(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["student_enrollment_id"], ["student_enrollments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_activities_lesson_id"),
        "learning_activities",
        ["lesson_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_activities_student_enrollment_id"),
        "learning_activities",
        ["student_enrollment_id"],
        unique=False,
    )
    op.create_table(
        "reminder_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_enrollment_id", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.Column("message_body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("tracking_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["student_enrollment_id"], ["student_enrollments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["teacher_id"], ["teachers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reminder_logs_lesson_id"), "reminder_logs", ["lesson_id"], unique=False
    )
    op.create_index(
        op.f("ix_reminder_logs_student_enrollment_id"),
        "reminder_logs",
        ["student_enrollment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reminder_logs_teacher_id"),
        "reminder_logs",
        ["teacher_id"],
        unique=False,
    )
    op.create_table(
        "recommendations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ai_insight_id", sa.UUID(), nullable=False),
        sa.Column("suggestion_text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("actioned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["ai_insight_id"], ["ai_insights.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendations_ai_insight_id"),
        "recommendations",
        ["ai_insight_id"],
        unique=False,
    )
    op.add_column(
        "teachers",
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=False,
            comment="Encrypted password hash",
        ),
    )
    op.add_column(
        "teachers",
        sa.Column(
            "failed_login_count",
            sa.Integer(),
            nullable=False,
            comment="Count of consecutive failed logins",
        ),
    )
    op.add_column(
        "teachers",
        sa.Column(
            "locked_until",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Account locked until timestamp",
        ),
    )
    op.add_column(
        "teachers", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column(
        "teachers",
        "id",
        existing_type=sa.UUID(),
        comment="UUID v4, PK",
        existing_nullable=False,
    )
    op.alter_column(
        "teachers",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment="Teacher's login email",
        existing_nullable=False,
    )
    op.alter_column(
        "teachers",
        "name",
        existing_type=sa.VARCHAR(length=255),
        comment="Teacher's full name",
        existing_nullable=False,
    )
    op.alter_column(
        "teachers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "teachers",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_column("teachers", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teachers",
        sa.Column(
            "hashed_password",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "teachers",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "teachers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "teachers",
        "name",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Teacher's full name",
        existing_nullable=False,
    )
    op.alter_column(
        "teachers",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Teacher's login email",
        existing_nullable=False,
    )
    op.alter_column(
        "teachers",
        "id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="UUID v4, PK",
        existing_nullable=False,
    )
    op.drop_column("teachers", "deleted_at")
    op.drop_column("teachers", "locked_until")
    op.drop_column("teachers", "failed_login_count")
    op.drop_column("teachers", "password_hash")
    op.drop_index(
        op.f("ix_recommendations_ai_insight_id"), table_name="recommendations"
    )
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_reminder_logs_teacher_id"), table_name="reminder_logs")
    op.drop_index(
        op.f("ix_reminder_logs_student_enrollment_id"), table_name="reminder_logs"
    )
    op.drop_index(op.f("ix_reminder_logs_lesson_id"), table_name="reminder_logs")
    op.drop_table("reminder_logs")
    op.drop_index(
        op.f("ix_learning_activities_student_enrollment_id"),
        table_name="learning_activities",
    )
    op.drop_index(
        op.f("ix_learning_activities_lesson_id"), table_name="learning_activities"
    )
    op.drop_table("learning_activities")
    op.drop_index(op.f("ix_ai_insights_lesson_id"), table_name="ai_insights")
    op.drop_table("ai_insights")
    op.drop_index(op.f("ix_lessons_module_id"), table_name="lessons")
    op.drop_index(op.f("ix_lessons_course_id"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(
        op.f("ix_student_enrollments_course_id"), table_name="student_enrollments"
    )
    op.drop_table("student_enrollments")
    op.drop_index(op.f("ix_modules_course_id"), table_name="modules")
    op.drop_table("modules")
    op.drop_index(op.f("ix_courses_teacher_id"), table_name="courses")
    op.drop_table("courses")
    op.drop_index(
        op.f("ix_udemy_connections_teacher_id"), table_name="udemy_connections"
    )
    op.drop_table("udemy_connections")
    op.drop_index(op.f("ix_data_imports_teacher_id"), table_name="data_imports")
    op.drop_table("data_imports")
    # ### end Alembic commands ###
